# Generated by Django 3.0.6 on 2020-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_author_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='rental.Author'),
        ),
    ]
