# Generated by Django 3.0.6 on 2020-05-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_borrowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
