# Generated by Django 3.0.6 on 2020-06-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_auto_20200613_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
