# Generated by Django 3.0.6 on 2020-06-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_auto_20200615_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_borrower',
            field=models.BooleanField(default=False),
        ),
    ]
