# Generated by Django 3.0.6 on 2020-06-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_user_is_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of genre such as Drama, Art...', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='XXXXXXXXXX', help_text='The ISBN of the Book - 13 Chars', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='rental.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='rental.Genre'),
        ),
    ]
