# Generated by Django 3.0.6 on 2020-06-18 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowed',
            options={'ordering': ['-borrowed_date']},
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('AR', 'ARABIC'), ('FR', 'FRENCH'), ('DE', 'GERMAN'), ('ES', 'SPANISH'), ('PT', 'PORTUGUESE')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 14, 17, 21, 430044), editable=False),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='rental.Author'),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.Book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='user',
            field=models.ForeignKey(help_text='username of the borrower', on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrowings', to=settings.AUTH_USER_MODEL),
        ),
    ]
