# Generated by Django 3.0.6 on 2020-06-18 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0017_auto_20200618_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 18, 42, 27, 948029)),
        ),
    ]
