# Generated by Django 3.0.6 on 2020-06-18 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_auto_20200618_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 18, 43, 20, 225789)),
        ),
    ]
