# Generated by Django 3.0.6 on 2020-06-19 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_auto_20200618_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 15, 24, 11, 217511)),
        ),
    ]
