# Generated by Django 3.0.6 on 2020-06-20 06:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_auto_20200620_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 6, 41, 51, 582729)),
        ),
    ]
