# Generated by Django 3.0.6 on 2020-06-20 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_auto_20200620_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 10, 33, 9, 478592)),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('isbn',), name='unique_isbn'),
        ),
    ]
