# Generated by Django 3.0.6 on 2020-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0026_auto_20200620_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed',
            name='due_back',
            field=models.DateTimeField(blank=True, editable=False, help_text='This field is not editable, it defaulted to day +1'),
        ),
    ]
